name: daily_quotes
description: QuoteSpace - Get inspired with quotes in your language every day.

publish_to: 'none'

version: 1.0.6+16

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.6
  shared_preferences: ^2.2.2
  share_plus: ^7.2.1
  flutter_local_notifications: ^18.0.0
  google_fonts: ^6.1.0
  timezone: ^0.9.2
  http: ^1.1.0
  google_mobile_ads: ^5.0.0
  in_app_purchase: ^3.1.13

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/app_icon.png"
  min_sdk_android: 21
  remove_alpha_ios: true
  # Android adaptive icon 설정
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/icon/app_icon.png"

flutter:
  uses-material-design: true
  
  assets:
    - assets/quotes.json
    - assets/quotes_translations.json
